# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Volumes/dfb_sandisk/Scripts/Python/camper/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setBold(True)
        font.setWeight(75)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lcdOutside = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdOutside.setGeometry(QtCore.QRect(600, 10, 64, 23))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(8)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.lcdOutside.setFont(font)
        self.lcdOutside.setAutoFillBackground(False)
        self.lcdOutside.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"font: 75 8pt \"MS Sans Serif\";\n"
"")
        self.lcdOutside.setDigitCount(3)
        self.lcdOutside.setProperty("intValue", 62)
        self.lcdOutside.setObjectName("lcdOutside")
        self.pbOutside = QtWidgets.QProgressBar(self.centralwidget)
        self.pbOutside.setGeometry(QtCore.QRect(110, 10, 481, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbOutside.setFont(font)
        self.pbOutside.setMinimum(-5)
        self.pbOutside.setMaximum(120)
        self.pbOutside.setProperty("value", 24)
        self.pbOutside.setObjectName("pbOutside")
        self.pbInside = QtWidgets.QProgressBar(self.centralwidget)
        self.pbInside.setGeometry(QtCore.QRect(110, 40, 481, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbInside.setFont(font)
        self.pbInside.setMinimum(-5)
        self.pbInside.setMaximum(120)
        self.pbInside.setProperty("value", 24)
        self.pbInside.setObjectName("pbInside")
        self.pbGarage = QtWidgets.QProgressBar(self.centralwidget)
        self.pbGarage.setGeometry(QtCore.QRect(110, 70, 481, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbGarage.setFont(font)
        self.pbGarage.setMinimum(-5)
        self.pbGarage.setMaximum(120)
        self.pbGarage.setProperty("value", 24)
        self.pbGarage.setObjectName("pbGarage")
        self.pbStorage = QtWidgets.QProgressBar(self.centralwidget)
        self.pbStorage.setGeometry(QtCore.QRect(110, 100, 481, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pbStorage.setFont(font)
        self.pbStorage.setMinimum(-15)
        self.pbStorage.setMaximum(120)
        self.pbStorage.setProperty("value", 25)
        self.pbStorage.setObjectName("pbStorage")
        self.lcdInside = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdInside.setGeometry(QtCore.QRect(600, 40, 64, 23))
        self.lcdInside.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"")
        self.lcdInside.setDigitCount(3)
        self.lcdInside.setObjectName("lcdInside")
        self.lcdGarage = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdGarage.setGeometry(QtCore.QRect(600, 70, 64, 23))
        self.lcdGarage.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.lcdGarage.setDigitCount(3)
        self.lcdGarage.setObjectName("lcdGarage")
        self.lblOutside = QtWidgets.QLabel(self.centralwidget)
        self.lblOutside.setGeometry(QtCore.QRect(20, 10, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblOutside.setFont(font)
        self.lblOutside.setTextFormat(QtCore.Qt.PlainText)
        self.lblOutside.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblOutside.setObjectName("lblOutside")
        self.lblInside = QtWidgets.QLabel(self.centralwidget)
        self.lblInside.setGeometry(QtCore.QRect(30, 40, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblInside.setFont(font)
        self.lblInside.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblInside.setObjectName("lblInside")
        self.lblGarage = QtWidgets.QLabel(self.centralwidget)
        self.lblGarage.setGeometry(QtCore.QRect(20, 70, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblGarage.setFont(font)
        self.lblGarage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGarage.setObjectName("lblGarage")
        self.lblStorage = QtWidgets.QLabel(self.centralwidget)
        self.lblStorage.setGeometry(QtCore.QRect(30, 100, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.lblStorage.setFont(font)
        self.lblStorage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblStorage.setObjectName("lblStorage")
        self.lcdStorage = QtWidgets.QLCDNumber(self.centralwidget)
        self.lcdStorage.setGeometry(QtCore.QRect(600, 100, 64, 23))
        self.lcdStorage.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.lcdStorage.setStyleSheet("background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 127);\n"
"gridline-color: rgb(0, 255, 0);\n"
"color: rgb(0, 255, 0);")
        self.lcdStorage.setDigitCount(3)
        self.lcdStorage.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.lcdStorage.setProperty("intValue", 78)
        self.lcdStorage.setObjectName("lcdStorage")
        self.btnGarage = QtWidgets.QPushButton(self.centralwidget)
        self.btnGarage.setGeometry(QtCore.QRect(60, 190, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnGarage.setFont(font)
        self.btnGarage.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btnGarage.setObjectName("btnGarage")
        self.btnStorage = QtWidgets.QPushButton(self.centralwidget)
        self.btnStorage.setGeometry(QtCore.QRect(170, 190, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnStorage.setFont(font)
        self.btnStorage.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btnStorage.setObjectName("btnStorage")
        self.btnAir = QtWidgets.QPushButton(self.centralwidget)
        self.btnAir.setGeometry(QtCore.QRect(280, 190, 80, 80))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btnAir.setFont(font)
        self.btnAir.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.btnAir.setObjectName("btnAir")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.pbStorage.valueChanged['int'].connect(self.lcdStorage.display)
        self.pbGarage.valueChanged['int'].connect(self.lcdGarage.display)
        self.pbInside.valueChanged['int'].connect(self.lcdInside.display)
        self.pbOutside.valueChanged['int'].connect(self.lcdOutside.display)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pbOutside.setFormat(_translate("MainWindow", "%v"))
        self.pbInside.setFormat(_translate("MainWindow", "%v"))
        self.pbGarage.setFormat(_translate("MainWindow", "%v"))
        self.pbStorage.setFormat(_translate("MainWindow", "%v"))
        self.lblOutside.setText(_translate("MainWindow", "Outside"))
        self.lblInside.setText(_translate("MainWindow", "Inside"))
        self.lblGarage.setText(_translate("MainWindow", "Garage"))
        self.lblStorage.setText(_translate("MainWindow", "Storage"))
        self.btnGarage.setText(_translate("MainWindow", "Garage\n"
" Fan"))
        self.btnStorage.setText(_translate("MainWindow", "Storage\n"
"Fan"))
        self.btnAir.setText(_translate("MainWindow", "A/C\n"
"Fan"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
